"""
metadata_utils.py: Utility functions for generating metadata strings.

Author: Nathan Lima
Date: 11/17/2025
Version: 1.0
Description: Provides functions to generate metadata strings with script execution
    timestamp and data quality flag summaries.

Usage:
    Import this module in your Python scripts to use the metadata functions.

"""

import os
import datetime


def get_script_metadata():
    """
    Generate metadata string with script execution timestamp.
    Gets the name of the calling script, not this utility script.

    Returns:
        str: Formatted timestamp string
    """
    # Try to get the calling script name using inspect module
    try:
        import inspect

        # Get the caller's frame (f_back) instead of current frame
        caller_frame = inspect.currentframe().f_back
        script_name = os.path.basename(inspect.getmodule(caller_frame).__file__)
    except (NameError, AttributeError, TypeError):
        # If inspect method fails, try __file__ approach from caller
        try:
            import inspect

            # Try to get caller's globals
            caller_frame = inspect.currentframe().f_back
            caller_globals = caller_frame.f_globals
            if "__file__" in caller_globals:
                script_name = os.path.basename(caller_globals["__file__"])
            else:
                script_name = "unknown_script_name"
        except (NameError, AttributeError, TypeError):
            # Final fallback
            script_name = "unknown_script_name"

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"Generated by: {script_name} | Date: {timestamp}"


def get_flag_metadata(flag_spans, flag_defs, sensor_name="sensor"):
    """
    Generate a metadata string summarizing data quality flag events for one sensor.

    Parameters:
        flag_spans (dict): {bit_value: [(t_start, t_end), ...]} produced by
            extract_flag_spans(). An empty dict means no flags were observed.
        flag_defs (dict): {bit_value: (label, color, alpha)} defining each flag.
        sensor_name (str): Human-readable sensor label (e.g., 'kitchen', 'bedroom').

    Returns:
        str: Pipe-delimited summary string suitable for embedding in a figure
            metadata annotation. Each flag that fired is listed with its
            time spans in hours since garage closed.
    """
    if not flag_spans:
        return f"{sensor_name.capitalize()} flags: none"

    parts = [f"{sensor_name.capitalize()} flags"]
    for bit, spans in sorted(flag_spans.items()):
        label = flag_defs[bit][0] if bit in flag_defs else f"bit {bit}"
        span_strs = [f"[{s:.3f}–{e:.3f} hrs]" for s, e in spans]
        parts.append(f"{label}: {', '.join(span_strs)}")

    return " | ".join(parts)
